### ISSUE TITLE
Socket write error

### ISSUE THREAD

**Issue by MeijeSibbel** [GooBox/goobox-community-gui#130]
### Versions

Replace the values below with your own:

- **GUI Version:** v0.2.0
- **Operating System:** windows 10
- **Storage provider selected:** Sia

Optional:

- **Current account balance:** <300SC>
- **Current wallet address:** <address>

![image](https://user-images.githubusercontent.com/11735738/40578479-e153a1b0-6114-11e8-9201-aef3199914de.png)

### logs

Please attach the following logs:

## windows

[sia-sync.log](https://github.com/GooBox/goobox-community-gui/files/2041779/sia-sync.log)
[log.log](https://github.com/GooBox/goobox-community-gui/files/2041780/log.log)

## Mac

....

## Linux

...

### Expected Behavior

Please describe the program's expected behavior.

```
No exception.
```

### Actual Behavior

Please describe the program's actual behavior. Please include any stack traces
or log output in the back ticks below.

```
[2018-05-26 18:40:48.322] [verbose] [Worker Thread 1] INFO  io.goobox.sync.sia.FileWatcher - Found modified file Fieldwork\GIS\Content teams\B6_Michalis_Emilio_geol.tif
[2018-05-26 18:40:48.330] [verbose] [pool-2-thread-18] ERROR c.l.n.control.win.MessageProcessor - Software caused connection abort: socket write error
[2018-05-26 18:40:48.330] [verbose] java.net.SocketException: Software caused connection abort: socket write error
[2018-05-26 18:40:48.330] [verbose] 	at java.net.SocketOutputStream.socketWrite0(Native Method)
[2018-05-26 18:40:48.330] [verbose] 	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
[2018-05-26 18:40:48.330] [verbose] 	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
[2018-05-26 18:40:48.330] [verbose] 	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
[2018-05-26 18:40:48.330] [verbose] 	at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:291)
[2018-05-26 18:40:48.331] [verbose] 	at sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:295)
[2018-05-26 18:40:48.331] [verbose] 	at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
[2018-05-26 18:40:48.331] [verbose] 	at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
[2018-05-26 18:40:48.331] [verbose] 	at com.fasterxml.jackson.core.json.WriterBasedJsonGenerator.close(WriterBasedJsonGenerator.java:929)
[2018-05-26 18:40:48.331] [verbose] 	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3898)
[2018-05-26 18:40:48.331] [verbose] 	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3189)
[2018-05-26 18:40:48.331] [verbose] 	at com.liferay.nativity.control.win.MessageProcessor._handle(MessageProcessor.java:98)
[2018-05-26 18:40:48.332] [verbose] 	at com.liferay.nativity.control.win.MessageProcessor.run(MessageProcessor.java:70)
[2018-05-26 18:40:48.332] [verbose] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[2018-05-26 18:40:48.332] [verbose] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[2018-05-26 18:40:48.332] [verbose] 	at java.lang.Thread.run(Thread.java:748)
[2018-05-26 18:40:48.333] [verbose] [Worker Thread 1] INFO  io.goobox.sync.sia.FileWatcher - Found modified file Fieldwork\photogrammetry\Articles\1-s2.0-S0040195117303426-main.pdf
```

### Steps to Reproduce

Please include the steps the reproduce the issue, numbered below. Include as
much detail as possible.

1. Place files in sync folder
2. ...
3. ...

### Screenshots (Optional)

If the error is graphical in nature it is helpful to provide a screenshot.

**Comment by jkawamoto** [comment]
Did overlay icons disappear after the error or did they still work expectedly?

**Comment by MeijeSibbel** [comment]
If i am not mistaken they only appeared after the error. I am not absolutely sure about this but there were like 10min where the overlay icons were gone. Then they reappeared.
