### ISSUE TITLE
Missing sync folder in changeStateHandler 

### ISSUE THREAD

**Issue by jkawamoto** [GooBox/goobox-community-gui#64]

**Comment by MeijeSibbel** [comment]
I think this issue persistes in v0.0.7:

```
2018-02-01 14:13:18 [main] INFO  io.goobox.sync.sia.Config - Sync directory: C:\Users\meije\Goobox
2018-02-01 14:13:18 [main] INFO  io.goobox.sync.sia.Config - Sync configuration: data pieces = 10, parity pieces = 20
2018-02-01 14:13:18 [main] INFO  io.goobox.sync.sia.App - Overwrite the sync directory: C:\Users\meije\Goobox
2018-02-01 14:13:18 [main] ERROR i.g.s.common.overlay.OverlayHelper - Cannot set system folder
java.nio.file.NoSuchFileException: C:\Users\meije\Goobox
    at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
    at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
    at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
    at sun.nio.fs.WindowsLinkSupport.getFinalPath(WindowsLinkSupport.java:107)
    at sun.nio.fs.WindowsFileAttributeViews$Dos.updateAttributes(WindowsFileAttributeViews.java:228)
    at sun.nio.fs.WindowsFileAttributeViews$Dos.setSystem(WindowsFileAttributeViews.java:263)
    at io.goobox.sync.common.overlay.OverlayHelper.<init>(OverlayHelper.java:69)
    at io.goobox.sync.sia.App.<init>(App.java:256)
    at io.goobox.sync.sia.App.main(App.java:188)
2018-02-01 14:13:18 [main] INFO  io.goobox.sync.sia.App - Checking if local Goobox sync folder exists: C:\Users\meije\Goobox
```

**Comment by jkawamoto** [comment]
v0.0.7 doesn’t embed newer sync-sia app, which means it haven’t been fixed yet. This issue is about pause/restart problem.
