### ISSUE TITLE
Sia seed box is empty

### ISSUE THREAD

**Issue by MeijeSibbel** [GooBox/goobox-community-gui#97]
[GooBoxLog.zip](https://github.com/GooBox/goobox-community-gui/files/1713686/GooBoxLog.zip)

**Comment by jkawamoto** [comment]
The reason of this issue is the following: 
```
[2018-02-09 19:29:28.480] [info] [GUI main] Starting goobox-sync-sia.bat in C:\Program Files\Goobox\resources\app\goobox-sync-sia\bin with --sync-dir,"K:\",--output-events
[2018-02-09 19:29:29.007] [verbose] Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <"> at index 2: K:" --output-events
[2018-02-09 19:29:29.007] [verbose] 	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
[2018-02-09 19:29:29.007] [verbose] 	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
[2018-02-09 19:29:29.008] [verbose] 	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
[2018-02-09 19:29:29.008] [verbose] 	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
[2018-02-09 19:29:29.008] [verbose] 	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
[2018-02-09 19:29:29.008] [verbose] 	at java.nio.file.Paths.get(Paths.java:84)
[2018-02-09 19:29:29.008] [verbose] 	at io.goobox.sync.sia.App.main(App.java:188)
```

**Comment by mranjan1** [comment]
Is there a way to fix it?

**Comment by jkawamoto** [comment]
I'm going to fix it but so far creating a folder fixes this issue, i.e. using `K:\Goobox` instead of `K:\`.
